version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: elearning
    container_name: elearning-app
    restart: unless-stopped
    working_dir: /var/www
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    command: php-fpm -y /usr/local/etc/php-fpm.conf -R

  nginx:
    image: nginx:alpine
    container_name: elearning-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker-compose/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/elearning/ssl/certbot:/var/www/certbot
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: elearning_db
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: vfl-academy
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: elearning-queue
    command: ./start-queue.sh
    restart: unless-stopped
    depends_on:
      - app
      - mysql
volumes:
  mysql_data:
