server {
    listen 80;
    server_name cms.viettech.click api.viettech.click;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name cms.viettech.click api.viettech.click;

    ssl_certificate /etc/letsencrypt/live/cms.viettech.click/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/cms.viettech.click/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    root /var/www/public;
    index index.php index.html;

    client_max_body_size 100M;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location /uploads/ {
        alias /var/www/public/uploads/;
        access_log off;
        expires 30d;
        add_header Cache-Control "public";
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    location ~ /\.ht {
        deny all;
    }

    error_log /var/log/nginx/api_error_log.log warn;
    access_log /var/log/nginx/access.log;
}
