server {
    listen 80;
    root /var/www/public;
    index index.php index.html;

    error_log /var/log/nginx/api_error_log.log debug;
    access_log /var/log/nginx/access.log;

    client_max_body_size 100M;

    # ⚠️ Đặt ở đây là sai:
    # add_header 'Access-Control-Allow-Origin' '*'; ❌

    location / {
        try_files $uri $uri/ /index.php?$query_string;

        # ✅ Đặt ở đây mới đúng
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE';
        add_header 'Access-Control-Allow-Headers' 'Content-Type, Authorization';
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    location ~ /\.ht {
        deny all;
    }
}
