server {
    listen 80;
    server_name elearning-cms.site www.elearning-cms.site;

    root /var/www/public;
    index index.php index.html;

    client_max_body_size 100M;

    # Cho phép Let's Encrypt truy cập xác thực file challenge
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Các request khác có thể trả về 404 hoặc text đơn giản
    location / {
        return 200 'Waiting for SSL certificate to be issued...';
        add_header Content-Type text/plain;
    }

    error_log /var/log/nginx/api_error_log.log debug;
    access_log /var/log/nginx/access.log;
}